`run_tolerances` modifies the inpout parameters
The same tolerances could not be used twice, because the analysis output
was added to the input dictionary. Thus, wehn running it a second time,
error like
ValueError: Object <arcus.defaults.DefaultPointing object at 0x7ff7cad4a438> does not have Aeff0 attribute.
would appear, because the analsys function added an Aeff and other values.
Now, the input parameter dist is copied so that that changes don't effect the
input list.